"use client";

import { useState } from 'react';
import { Camera, ChevronRight, Ruler, Sparkles, UserRound, Shirt, Palette, Plus, Check } from 'lucide-react';

const measurements = [['Height','178','cm'],['Chest','102','cm'],['Waist','88','cm'],['Shoulder','45','cm'],['Shirt Length','74','cm'],['Sleeve','62','cm'],['Pant Waist','88','cm'],['Pant Length','103','cm']];
const colors = [{name:'Navy',hex:'#17243a'},{name:'Charcoal',hex:'#343638'},{name:'Sky Blue',hex:'#9fb9c8'},{name:'Beige',hex:'#c7b79d'},{name:'White',hex:'#f4f3ee'},{name:'Olive',hex:'#65705b'}];

export default function Home(){
 const [tab,setTab]=useState<'shirt'|'pant'>('shirt'); const [selected,setSelected]=useState('Navy');
 return <main className="min-h-screen bg-[#faf9f7]">
  <header className="border-b border-stone-200 bg-white"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-8 py-5"><div><div className="text-[11px] font-bold uppercase tracking-[.28em] text-[#b8894b]">SMART TAILOR</div><h1 className="mt-1 text-xl font-semibold tracking-tight">AI Fitting Studio</h1></div><div className="flex items-center gap-3"><button className="rounded-full border border-stone-200 px-4 py-2 text-sm">Customers</button><button className="rounded-full bg-[#171717] px-5 py-2 text-sm text-white">+ New customer</button></div></div></header>
  <div className="mx-auto max-w-[1400px] px-8 py-8"><div className="mb-8 flex items-end justify-between"><div><p className="text-sm text-stone-500">Customer workspace</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">New Fitting</h2></div><div className="flex items-center gap-2 text-sm text-stone-500"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#171717] text-white">1</span> Measurements <ChevronRight size={15}/><span className="flex h-7 w-7 items-center justify-center rounded-full border border-stone-300">2</span> Style <ChevronRight size={15}/><span className="flex h-7 w-7 items-center justify-center rounded-full border border-stone-300">3</span> Preview</div></div>
   <div className="grid gap-6 lg:grid-cols-[360px_1fr_330px]">
    <section className="rounded-2xl border border-stone-200 bg-white p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-semibold">Measurements</h3><p className="mt-1 text-xs text-stone-500">Enter tailor-verified measurements</p></div><Ruler size={20} className="text-stone-400"/></div><div className="grid grid-cols-2 gap-3">{measurements.map(([label,value,unit])=><label key={label} className="text-xs font-medium text-stone-600">{label}<div className="mt-1 flex items-center rounded-xl border border-stone-200 bg-stone-50 px-3"><input defaultValue={value} className="w-full bg-transparent py-2.5 text-sm font-semibold outline-none"/><span className="text-[10px] text-stone-400">{unit}</span></div></label>)}</div><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-stone-300 py-3 text-sm font-medium text-stone-600"><Camera size={17}/> Scan with camera <span className="rounded bg-stone-100 px-1.5 py-0.5 text-[9px] uppercase">Soon</span></button></section>
    <section className="relative min-h-[600px] overflow-hidden rounded-2xl border border-stone-200 bg-[#eeeae3] p-6"><div className="absolute inset-0 opacity-30" style={{backgroundImage:'linear-gradient(#d6d0c7 1px, transparent 1px),linear-gradient(90deg,#d6d0c7 1px,transparent 1px)',backgroundSize:'40px 40px'}}/><div className="relative flex h-full min-h-[550px] flex-col items-center justify-center"><div className="absolute left-5 top-5 flex items-center gap-2 rounded-full bg-white/85 px-3 py-1.5 text-xs font-medium backdrop-blur"><Sparkles size={14} className="text-[#b8894b]"/> AI Preview</div><div className="relative flex h-[430px] w-[210px] flex-col items-center justify-center"><div className="h-20 w-20 rounded-full bg-[#b99a80] shadow-inner"/><div className="mt-[-3px] h-[270px] w-[180px] rounded-[48%_48%_18%_18%] bg-gradient-to-b from-[#17243a] to-[#263852] shadow-xl"/><div className="mt-[-10px] flex gap-4"><div className="h-32 w-12 rounded-b-3xl bg-[#292b2f]"/><div className="h-32 w-12 rounded-b-3xl bg-[#292b2f]"/></div><div className="absolute top-[98px] h-2 w-28 rounded-full bg-white/20"/></div><p className="mt-4 text-xs text-stone-500">Personalized avatar preview</p></div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-6"><div className="mb-5"><h3 className="font-semibold">Style Studio</h3><p className="mt-1 text-xs text-stone-500">Build the look before cutting fabric</p></div><div className="flex rounded-xl bg-stone-100 p-1">{(['shirt','pant'] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`flex-1 rounded-lg py-2 text-xs font-semibold capitalize ${tab===x?'bg-white shadow-sm':''}`}><span className="flex items-center justify-center gap-2">{x==='shirt'?<Shirt size={15}/>:<UserRound size={15}/>} {x}</span></button>)}</div><div className="mt-5 space-y-4"><label className="block text-xs font-medium text-stone-600">Fit<select className="mt-1 w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none"><option>Modern Regular</option><option>Slim Fit</option><option>Relaxed</option></select></label><label className="block text-xs font-medium text-stone-600">{tab==='shirt'?'Collar':'Rise'}<select className="mt-1 w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none"><option>{tab==='shirt'?'Spread Collar':'Mid Rise'}</option><option>{tab==='shirt'?'Cutaway Collar':'High Rise'}</option></select></label><div><div className="mb-2 flex items-center justify-between text-xs font-medium text-stone-600"><span>Colour</span><Palette size={15} className="text-stone-400"/></div><div className="grid grid-cols-3 gap-2">{colors.map(c=><button key={c.name} onClick={()=>setSelected(c.name)} title={c.name} className={`relative h-9 rounded-lg border ${selected===c.name?'border-[#b8894b] ring-2 ring-[#b8894b]/20':'border-stone-200'}`} style={{background:c.hex}}>{selected===c.name&&<Check size={15} className="absolute inset-0 m-auto text-white drop-shadow"/>}</button>)}</div><p className="mt-2 text-[11px] text-stone-400">Selected: {selected}</p></div></div><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#171717] py-3 text-sm font-semibold text-white"><Sparkles size={16}/> Generate AI Preview</button></section>
   </div>
   <div className="mt-6 grid gap-6 md:grid-cols-3"><div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs text-stone-400">BODY PROFILE</p><p className="mt-2 text-lg font-semibold">Balanced build</p><p className="mt-1 text-xs text-stone-500">Based on entered measurements</p></div><div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs text-stone-400">AI COLOUR MATCH</p><p className="mt-2 text-lg font-semibold">Navy · 96%</p><p className="mt-1 text-xs text-stone-500">Strong versatile recommendation</p></div><div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs text-stone-400">NEXT STEP</p><p className="mt-2 flex items-center gap-2 text-lg font-semibold">Generate preview <Plus size={18}/></p><p className="mt-1 text-xs text-stone-500">AI garment visualization will plug in here</p></div></div>
  </div>
 </main>
}
