"use client";

import { ChangeEvent, useMemo, useState } from 'react';
import { Camera, ChevronRight, Ruler, Sparkles, UserRound, Shirt, Palette, Plus, Check, Upload, Loader2 } from 'lucide-react';

const measurementFields = [
  ['height','Height','178','cm'],['chest','Chest','102','cm'],['waist','Waist','88','cm'],['shoulder','Shoulder','45','cm'],
  ['shirtLength','Shirt Length','74','cm'],['sleeve','Sleeve','62','cm'],['pantWaist','Pant Waist','88','cm'],['pantLength','Pant Length','103','cm'],
  ['thigh','Thigh','58','cm'],['knee','Knee','42','cm'],['bottom','Bottom','38','cm'],['neck','Neck','40','cm'],
] as const;
const colors = [{name:'Navy',hex:'#17243a'},{name:'Charcoal',hex:'#343638'},{name:'Sky Blue',hex:'#9fb9c8'},{name:'Beige',hex:'#c7b79d'},{name:'White',hex:'#f4f3ee'},{name:'Olive',hex:'#65705b'}];

type Photo = { name: string; url: string };

export default function Home(){
 const [tab,setTab]=useState<'shirt'|'pant'>('shirt');
 const [selected,setSelected]=useState('Navy');
 const [fit,setFit]=useState('Modern Regular');
 const [detail,setDetail]=useState('Spread Collar');
 const [measurements,setMeasurements]=useState<Record<string,string>>(() => Object.fromEntries(measurementFields.map(([key,,value])=>[key,value])));
 const [frontPhoto,setFrontPhoto]=useState<Photo | null>(null);
 const [sidePhoto,setSidePhoto]=useState<Photo | null>(null);
 const [loading,setLoading]=useState(false);
 const [result,setResult]=useState<{bodyProfile:string;colorName:string;score:number;message:string}|null>(null);
 const color=colors.find(c=>c.name===selected)!;

 const handlePhoto=(setter:(p:Photo|null)=>void)=>(e:ChangeEvent<HTMLInputElement>)=>{
   const file=e.target.files?.[0]; if(!file) return;
   const reader=new FileReader(); reader.onload=()=>setter({name:file.name,url:String(reader.result)}); reader.readAsDataURL(file);
 };
 const numericMeasurements=useMemo(()=>Object.fromEntries(Object.entries(measurements).map(([k,v])=>[k,Number(v)||0])),[measurements]);
 const generate=async()=>{
   setLoading(true); setResult(null);
   try{
     const res=await fetch('/api/virtual-try-on',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({measurements:numericMeasurements,garment:{garment:tab,fit,detail,colorName:selected,colorHex:color.hex},photoDataUrl:frontPhoto?.url,sidePhotoDataUrl:sidePhoto?.url})});
     const data=await res.json(); if(!res.ok) throw new Error(data.error||'Preview failed'); setResult(data);
   }catch(e){setResult({bodyProfile:'Unable to calculate',colorName:selected,score:0,message:e instanceof Error?e.message:'Preview failed'});}
   finally{setLoading(false);}
 };
 return <main className="min-h-screen bg-[#faf9f7]">
  <header className="border-b border-stone-200 bg-white"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-8 py-5"><div><div className="text-[11px] font-bold uppercase tracking-[.28em] text-[#b8894b]">SMART TAILOR</div><h1 className="mt-1 text-xl font-semibold tracking-tight">AI Fitting Studio</h1></div><div className="flex items-center gap-3"><button className="rounded-full border border-stone-200 px-4 py-2 text-sm">Customers</button><button className="rounded-full bg-[#171717] px-5 py-2 text-sm text-white">+ New customer</button></div></div></header>
  <div className="mx-auto max-w-[1400px] px-8 py-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm text-stone-500">Customer workspace</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">New Fitting</h2></div><div className="flex items-center gap-2 text-sm text-stone-500"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#171717] text-white">1</span> Measurements <ChevronRight size={15}/><span className="flex h-7 w-7 items-center justify-center rounded-full border border-stone-300">2</span> Style <ChevronRight size={15}/><span className="flex h-7 w-7 items-center justify-center rounded-full border border-stone-300">3</span> Preview</div></div>
   <div className="grid gap-6 lg:grid-cols-[360px_1fr_330px]">
    <section className="rounded-2xl border border-stone-200 bg-white p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-semibold">Measurements</h3><p className="mt-1 text-xs text-stone-500">Enter tailor-verified measurements</p></div><Ruler size={20} className="text-stone-400"/></div><div className="grid grid-cols-2 gap-3">{measurementFields.map(([key,label,value,unit])=><label key={key} className="text-xs font-medium text-stone-600">{label}<div className="mt-1 flex items-center rounded-xl border border-stone-200 bg-stone-50 px-3"><input value={measurements[key]} onChange={e=>setMeasurements(m=>({...m,[key]:e.target.value}))} className="w-full bg-transparent py-2.5 text-sm font-semibold outline-none"/><span className="text-[10px] text-stone-400">{unit}</span></div></label>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-stone-300 py-3 text-xs font-medium text-stone-600"><Upload size={15}/> Front photo<input type="file" accept="image/*" className="hidden" onChange={handlePhoto(setFrontPhoto)}/></label><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-stone-300 py-3 text-xs font-medium text-stone-600"><Upload size={15}/> Side photo<input type="file" accept="image/*" className="hidden" onChange={handlePhoto(setSidePhoto)}/></label></div><div className="mt-3 flex gap-2">{frontPhoto&&<img src={frontPhoto.url} alt="Front customer" className="h-16 w-12 rounded-lg object-cover"/>}{sidePhoto&&<img src={sidePhoto.url} alt="Side customer" className="h-16 w-12 rounded-lg object-cover"/>}<button className="flex items-center gap-2 rounded-lg border border-stone-200 px-3 text-xs text-stone-500"><Camera size={15}/> Camera <span className="rounded bg-stone-100 px-1.5 py-0.5 text-[9px] uppercase">Soon</span></button></div></section>
    <section className="relative min-h-[600px] overflow-hidden rounded-2xl border border-stone-200 bg-[#eeeae3] p-6"><div className="absolute inset-0 opacity-30" style={{backgroundImage:'linear-gradient(#d6d0c7 1px, transparent 1px),linear-gradient(90deg,#d6d0c7 1px,transparent 1px)',backgroundSize:'40px 40px'}}/><div className="relative flex h-full min-h-[550px] flex-col items-center justify-center"><div className="absolute left-5 top-5 flex items-center gap-2 rounded-full bg-white/85 px-3 py-1.5 text-xs font-medium backdrop-blur"><Sparkles size={14} className="text-[#b8894b]"/> AI Preview</div>{frontPhoto?<div className="relative h-[440px] w-[300px] overflow-hidden rounded-2xl bg-white shadow-xl"><img src={frontPhoto.url} alt="Customer preview" className="h-full w-full object-contain"/><div className="absolute inset-x-5 bottom-5 rounded-xl bg-white/90 p-3 text-center text-xs font-medium backdrop-blur">{result?'AI garment preview ready':'Photo reference · preview mode'}</div></div>:<div className="relative flex h-[430px] w-[210px] flex-col items-center justify-center"><div className="h-20 w-20 rounded-full bg-[#b99a80] shadow-inner"/><div className="mt-[-3px] h-[270px] w-[180px] rounded-[48%_48%_18%_18%] shadow-xl" style={{background:`linear-gradient(to bottom, ${color.hex}, #263852)`}}/><div className="mt-[-10px] flex gap-4"><div className="h-32 w-12 rounded-b-3xl bg-[#292b2f]"/><div className="h-32 w-12 rounded-b-3xl bg-[#292b2f]"/></div></div>}<p className="mt-4 text-xs text-stone-500">{result?.message||'Personalized avatar preview'}</p></div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-6"><div className="mb-5"><h3 className="font-semibold">Style Studio</h3><p className="mt-1 text-xs text-stone-500">Build the look before cutting fabric</p></div><div className="flex rounded-xl bg-stone-100 p-1">{(['shirt','pant'] as const).map(x=><button key={x} onClick={()=>{setTab(x);setDetail(x==='shirt'?'Spread Collar':'Mid Rise')}} className={`flex-1 rounded-lg py-2 text-xs font-semibold capitalize ${tab===x?'bg-white shadow-sm':''}`}><span className="flex items-center justify-center gap-2">{x==='shirt'?<Shirt size={15}/>:<UserRound size={15}/>} {x}</span></button>)}</div><div className="mt-5 space-y-4"><label className="block text-xs font-medium text-stone-600">Fit<select value={fit} onChange={e=>setFit(e.target.value)} className="mt-1 w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none"><option>Modern Regular</option><option>Slim Fit</option><option>Relaxed</option></select></label><label className="block text-xs font-medium text-stone-600">{tab==='shirt'?'Collar':'Rise'}<select value={detail} onChange={e=>setDetail(e.target.value)} className="mt-1 w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none">{tab==='shirt'?<><option>Spread Collar</option><option>Cutaway Collar</option><option>Mandarin Collar</option></>:<><option>Mid Rise</option><option>High Rise</option><option>Low Rise</option></>}</select></label><div><div className="mb-2 flex items-center justify-between text-xs font-medium text-stone-600"><span>Colour</span><Palette size={15} className="text-stone-400"/></div><div className="grid grid-cols-3 gap-2">{colors.map(c=><button key={c.name} onClick={()=>setSelected(c.name)} title={c.name} className={`relative h-9 rounded-lg border ${selected===c.name?'border-[#b8894b] ring-2 ring-[#b8894b]/20':'border-stone-200'}`} style={{background:c.hex}}>{selected===c.name&&<Check size={15} className="absolute inset-0 m-auto text-white drop-shadow"/>}</button>)}</div><p className="mt-2 text-[11px] text-stone-400">Selected: {selected}</p></div></div><button onClick={generate} disabled={loading} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#171717] py-3 text-sm font-semibold text-white disabled:opacity-60">{loading?<><Loader2 size={16} className="animate-spin"/> Generating…</>:<><Sparkles size={16}/> Generate AI Preview</>}</button></section>
   </div>
   <div className="mt-6 grid gap-6 md:grid-cols-3"><div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs text-stone-400">BODY PROFILE</p><p className="mt-2 text-lg font-semibold">{result?.bodyProfile||'Balanced build'}</p><p className="mt-1 text-xs text-stone-500">Based on entered measurements</p></div><div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs text-stone-400">AI COLOUR MATCH</p><p className="mt-2 text-lg font-semibold">{result?`${result.colorName} · ${result.score}%`:'Navy · 96%'}</p><p className="mt-1 text-xs text-stone-500">{result?.message||'Strong versatile recommendation'}</p></div><div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs text-stone-400">NEXT STEP</p><p className="mt-2 flex items-center gap-2 text-lg font-semibold">{loading?'Generating preview':'Preview garment'} <Plus size={18}/></p><p className="mt-1 text-xs text-stone-500">{frontPhoto?'Photo reference attached':'Add a front photo for personalized visualization'}</p></div></div>
  </div>
 </main>
}
